/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.VitalSigns;
import model.VitalSignsHistory;

/**
 *
 * @author tiankaining
 */
public class ViewPanel extends javax.swing.JPanel {
    VitalSignsHistory vitalSignsHistory;

    /**
     * Creates new form ViewPanel
     */
    public ViewPanel(VitalSignsHistory vitalSignsHistory) {
        initComponents();
        this.vitalSignsHistory = vitalSignsHistory;
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTemp = new javax.swing.JLabel();
        txtTemp = new javax.swing.JTextField();
        txtBldP = new javax.swing.JTextField();
        lblBldP = new javax.swing.JLabel();
        txtPul = new javax.swing.JTextField();
        lblPul = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        lblDate = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        btnDelet = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVitals = new javax.swing.JTable();

        lblTemp.setText("Temperature:");

        lblBldP.setText("Blood Pressure:");

        lblPul.setText("Pulse:");

        lblDate.setText("Date:");

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblTitle.setText("Create Vital Signs");

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnDelet.setText("Delet");
        btnDelet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletActionPerformed(evt);
            }
        });

        tblVitals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Temperature", "BloodPressure", "Pulse"
            }
        ));
        jScrollPane1.setViewportView(tblVitals);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblBldP)
                            .addComponent(lblPul)
                            .addComponent(lblTemp)
                            .addComponent(lblDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBldP, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPul, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnView)
                            .addComponent(btnDelet))))
                .addGap(134, 134, 134))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblTemp))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnView))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBldP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBldP)
                            .addComponent(btnDelet))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPul))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDate))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        // 获取表格中选中的行索引
        int selectedIndex = tblVitals.getSelectedRow();
        // 如果未选中任何行，弹出警告对话框
        if (selectedIndex < 0) {
        JOptionPane.showMessageDialog(this, 
            "Please select a row first", 
            "Warning", 
            JOptionPane.WARNING_MESSAGE);
        return;
        }
        // 获取表格模型和选中的 VitalSigns 对象
        DefaultTableModel model = (DefaultTableModel) tblVitals.getModel();
        // 从 vitalSignsHistory 中获取选中的 VitalSigns 对象
        VitalSigns selectedVitals = vitalSignsHistory.getHistory().get(selectedIndex);
    
        // 如果选中的对象不为空，将其属性显示到对应的文本框
        if (selectedVitals != null) {
        txtTemp.setText(Double.toString(selectedVitals.getTemperature()));
        txtBldP.setText(Double.toString(selectedVitals.getBloodPressure()));
        txtPul.setText(Integer.toString(selectedVitals.getPulse()));
        txtDate.setText(selectedVitals.getDate());
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnDeletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletActionPerformed
        // TODO add your handling code here:
        // 获取表格中选中的行索引
        int selectedIndex = tblVitals.getSelectedRow();
        // 如果未选中任何行，弹出警告对话框
        if (selectedIndex < 0) {
        JOptionPane.showMessageDialog(this, 
            "Please select a row first", 
            "Warning", 
            JOptionPane.WARNING_MESSAGE);
        return;
        }
        // 获取表格模型和选中的 VitalSigns 对象
        DefaultTableModel model = (DefaultTableModel) tblVitals.getModel();
        // 从 vitalSignsHistory 中获取选中的 VitalSigns 对象
        VitalSigns selectedVitals = vitalSignsHistory.getHistory().get(selectedIndex);
        
        //Implement the deletion
        if (selectedVitals != null) {
        vitalSignsHistory.removeVitals(selectedVitals);
        JOptionPane.showMessageDialog(this, "Vital signs deleted!", "Success", JOptionPane.WARNING_MESSAGE);
        }
        //update table
        populateTable();
    }//GEN-LAST:event_btnDeletActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelet;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBldP;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblPul;
    private javax.swing.JLabel lblTemp;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblVitals;
    private javax.swing.JTextField txtBldP;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtPul;
    private javax.swing.JTextField txtTemp;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        // 获取表格的默认模型
        DefaultTableModel model = (DefaultTableModel) tblVitals.getModel();
    
        // 清空表格中的所有行
        model.setRowCount(0);
    
        // 遍历 vitalSignsHistory 中的历史记录
        for (VitalSigns vs : vitalSignsHistory.getHistory()) {
        Object[] row = new Object[4];// 创建一个包含4个元素的数组，表示一行数据
        row[0] = vs;          
        row[1] = vs.getTemperature();   
        row[2] = vs.getBloodPressure(); 
        row[3] = vs.getPulse();         
        
        // 将这一行数据添加到表格模型中
        model.addRow(row);
        }
    }
}
