/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.AccountManager;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Account;
import model.AccountDirectory;

/**
 *
 * @author tiankaining
 */
public class ManageAccountsJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    AccountDirectory accountDirectory;

    /**
     * Creates new form ManageAccountsJPanel
     */
    public ManageAccountsJPanel(JPanel container, AccountDirectory directory) {
        initComponents();
        
        userProcessContainer = container;
        accountDirectory = directory;
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAccounts = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        btnViewDetails = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtSearchBox = new javax.swing.JTextField();

        lblTitle.setText("Manage Account");

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblAccounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Bank Name", "Routing Number", "Account Number", "Balance"
            }
        ));
        jScrollPane1.setViewportView(tblAccounts);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnViewDetails.setText("View Details");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete Account");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(270, 270, 270)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnViewDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(txtSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete)
                .addContainerGap(250, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        // 1. 从 userProcessContainer 中移除当前面板
        userProcessContainer.remove(this);
        // 2. 获取 userProcessContainer 的布局管理器（必须是 CardLayout）
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        // 3. 切换到前一个面板
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblAccounts.getSelectedRow();
        if (selectedRow >= 0) {
            String bankName = (String) tblAccounts.getValueAt(selectedRow, 0);
            String routingNumber = (String) tblAccounts.getValueAt(selectedRow, 1);

            // 通过银行名称和路由号码查找对应的账户
            Account selectedAccount = null;
            for (Account acc : accountDirectory.getAccounts()) {
                if (acc.getBankName().equals(bankName) && 
                    acc.getRoutingNumber().equals(routingNumber)) {
                    selectedAccount = acc;
                    break;
                }
            }

            if (selectedAccount != null) {
                ViewAccountJPanel viewPanel = new ViewAccountJPanel(userProcessContainer, accountDirectory, selectedAccount);
                userProcessContainer.add("ViewAccountJPanel", viewPanel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select an account from the list to view.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        // 获取用户选中的行
            int selectedRow = tblAccounts.getSelectedRow();

            // 检查是否有选中的行
            if (selectedRow >= 0) {
            // 弹出确认对话框
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(
            null, 
            "Are you sure you want to delete the selected account?", 
            "Warning", 
            dialogButton
            );

            // 如果用户点击“是”
            if (dialogResult == JOptionPane.YES_OPTION) {
                // 获取选中行的账户对象
                Account selectedAccount = (Account) tblAccounts.getValueAt(selectedRow, 0); // 假设账户对象在第一列

                // 从 accountDirectory 中删除账户
                accountDirectory.deleteAccount(selectedAccount);

                // 刷新表格数据
                populateTable();
            }
        } else {
        // 如果没有选中的行，显示警告消息
        JOptionPane.showMessageDialog(
            null, 
            "Please select an account from the list.", 
            "Warning", 
            JOptionPane.WARNING_MESSAGE
        );
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // 获取搜索框中的文本
        String searchText = txtSearchBox.getText().trim().toLowerCase();

        if (searchText.isEmpty()) {
            // 如果搜索框为空，显示所有数据
            populateTable();
            return;
        }

        // 获取表格模型
        DefaultTableModel model = (DefaultTableModel) tblAccounts.getModel();
        // 清空现有数据
        model.setRowCount(0);

        // 遍历所有账户，查找匹配项
        for (Account a : accountDirectory.getAccounts()) {
            // 检查银行名称、路由号码或账户号码是否包含搜索文本
            if (a.getBankName().toLowerCase().contains(searchText) ||
                a.getRoutingNumber().toLowerCase().contains(searchText) ||
                a.getAccountNumber().toLowerCase().contains(searchText)) {

                Object[] row = new Object[4];
                row[0] = a.getBankName();
                row[1] = a.getRoutingNumber();
                row[2] = a.getAccountNumber();
                row[3] = String.valueOf(a.getBalance());
                model.addRow(row);
            }
        }

        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "No matching accounts found.", "Search Result", JOptionPane.INFORMATION_MESSAGE);
            // 可选：如果没有找到匹配项，恢复显示所有数据
            populateTable();
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void populateTable() {
        // 获取表格的默认模型
        DefaultTableModel model = (DefaultTableModel) tblAccounts.getModel();

        // 清空表格中的所有行
        model.setRowCount(0);

        // 遍历 accountDirectory 中的账户数据
            for (Account a : accountDirectory.getAccounts()) {
            Object[] row = new Object[4];
            row[0] = a.getBankName();      // 银行名称放在第一列
            row[1] = a.getRoutingNumber(); // 路由号码
            row[2] = a.getAccountNumber(); // 账户号码
            row[3] = String.valueOf(a.getBalance());

            // 将这一行数据添加到表格模型中
            model.addRow(row);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblAccounts;
    private javax.swing.JTextField txtSearchBox;
    // End of variables declaration//GEN-END:variables
}
